package:
  name: softlayer
  version: "4.1.1"

source:
  fn: SoftLayer-4.1.1.tar.gz
  url: https://pypi.python.org/packages/source/S/SoftLayer/SoftLayer-4.1.1.tar.gz
  md5: 0851ef6e353883368d759ae841371897

build:
  entry_points:
    - slcli = SoftLayer.CLI.core:main
    - sl = SoftLayer.CLI.deprecated:main

requirements:
  build:
    - python
    - setuptools
    - six >=1.7.0
    - prettytable >=0.7.0
    - click >=5
    - requests >=2.7.0
    - prompt_toolkit

  run:
    - python
    - six >=1.7.0
    - prettytable >=0.7.0
    - click >=5
    - requests >=2.7.0
    - prompt_toolkit

test:
  requires:
    - mock
    - testtools

  imports:
    - SoftLayer
    - SoftLayer.CLI
    - SoftLayer.CLI.cdn
    - SoftLayer.CLI.config
    - SoftLayer.CLI.dns
    - SoftLayer.CLI.firewall
    - SoftLayer.CLI.globalip
    - SoftLayer.CLI.image
    - SoftLayer.CLI.iscsi
    - SoftLayer.CLI.loadbal
    - SoftLayer.CLI.mq
    - SoftLayer.CLI.nas
    - SoftLayer.CLI.rwhois
    - SoftLayer.CLI.server
    - SoftLayer.CLI.snapshot
    - SoftLayer.CLI.sshkey
    - SoftLayer.CLI.ssl
    - SoftLayer.CLI.subnet
    - SoftLayer.CLI.ticket
    - SoftLayer.CLI.virt
    - SoftLayer.CLI.vlan
    - SoftLayer.fixtures
    - SoftLayer.managers
    - SoftLayer.shell
    - SoftLayer.testing

  commands:
    - slcli --help
    # WARNING: "sl" will always fail, as "slcli" is now the preferred client.
    #- sl --help

about:
  home: http://github.com/softlayer/softlayer-python
  license: MIT License
  summary: "Python libraries and CLI tools for SoftLayer's API"
