package:
  name: extras
  version: "0.0.3"

source:
  fn: extras-0.0.3.tar.gz
  url: https://pypi.python.org/packages/source/e/extras/extras-0.0.3.tar.gz
  md5: "62d8ba049e3386a6df69b413ea81517b"

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - extras
    - extras.tests

about:
  home: https://github.com/testing-cabal/extras
  license: MIT License
  summary: 'Useful extra bits for Python'
