package:
  name: click
  version: "5.1"

source:
  fn: click-5.1.tar.gz
  url: https://pypi.python.org/packages/source/c/click/click-5.1.tar.gz
  md5: 9c5323008cccfe232a8b161fc8196d41

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - click

about:
  home: http://github.com/mitsuhiko/click
  license: BSD License
  summary: 'Simple wrapper around optparse for powerful command line utilities.'
