package:
  name: testtools
  version: "1.8.1"

source:
  fn: testtools-1.8.1.tar.gz
  url: https://pypi.python.org/packages/source/t/testtools/testtools-1.8.1.tar.gz
  md5: "6c881bf2ce1635ed6fcd96e57262bf48"

requirements:
  build:
    - python
    - setuptools
    - pbr

  run:
    - python
    - pbr
    - extras

about:
  home: https://testtools.readthedocs.org/en/latest/
  license: MIT License
  summary: 'Extensions to the Python standard library unit testing framework'
