package:
  name: python-swiftclient
  version: "2.7.0"

source:
  fn: python-swiftclient-2.7.0.tar.gz
  url: https://pypi.python.org/packages/source/p/python-swiftclient/python-swiftclient-2.7.0.tar.gz
  md5: "e04710f3a74dccefd64bc75f866dd37e"

requirements:
  build:
    - python
    - setuptools
    - pbr

  run:
    - python
    - requests
    - six
    - futures   # [py2k]

test:
  commands:
    - swift --help

about:
  home: "https://github.com/openstack/python-swiftclient"
  license: Apache Software License
  summary: 'OpenStack Object Storage API Client Library'
