package:
  name: prettytable
  version: "0.7.2"

source:
  fn: prettytable-0.7.2.tar.bz2
  url: https://pypi.python.org/packages/source/P/PrettyTable/prettytable-0.7.2.tar.bz2
  md5: 760dc900590ac3c46736167e09fa463a

requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  home: http://code.google.com/p/prettytable
  license: BSD License
  summary: 'Simple Python library for displaying tabular data in a visually appealing ASCII table format'
