{% set name = "netaddr" %}
{% set version = "0.8.0" %}
{% set sha256 = "d6cc57c7a07b1d9d2e917aa8b36ae8ce61c35ba3fcd1b83ca31c5a0ee2b5a243" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  fn: "{{ name|lower }}-{{ version }}.tar.gz"
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "{{ sha256 }}"

build:
  number: 0
  noarch: python
  entry_points:
    - netaddr = netaddr.cli:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.0
    - pip
  run:
    - python

test:
  imports:
    - netaddr
    - netaddr.contrib
    - netaddr.eui
    - netaddr.ip
    - netaddr.strategy
  # Skipping since this launches an interactive iPython shell
  #commands:
  #  - netaddr --help

about:
  home: "https://github.com/drkjam/netaddr/"
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: "A network address manipulation library for Python"
  doc_url: "https://netaddr.readthedocs.io/en/latest/"
  dev_url: "https://github.com/netaddr/netaddr"

extra:
  recipe-maintainers:
    - chenghlee
